# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["api", "migration", "entity", "views"]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["Samuel O. Silva <samuel@slva.fr>"]

[workspace.lints.rust]
unsafe_code = "forbid"
