networks:
  main: {}

volumes:
  db-data: {}

services:
  web:
    build:
      context: .
      dockerfile: Local.Dockerfile
    depends_on:
      - db
      - keycloak
    environment:
      DATABASE_URL: postgres://postgres:assowrd@db/rust-todo
      OAUTH_ISSUER: https://balanced-elk-76.clerk.accounts.dev
      RUST_LOG: DEBUG
      PORT: "8080"
    ports:
      - "8080:8080"
    networks:
      - main
  keycloak:
    image: bitnami/keycloak:24
    restart: unless-stopped
    environment:
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_ADMIN_PASSWORD=keycloak
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_DATABASE_HOST=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - main
    ports:
      - 8888:8080
  db:
    image: "postgres:16"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: rust-todo
      POSTGRES_PASSWORD: assowrd
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      - ./migration/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - main
