networks:
  main: {}

volumes:
  db-data: {}

services:
  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:assowrd@db/rust-todo
      OAUTH_ISSUER: https://balanced-elk-76.clerk.accounts.dev
      RUST_LOG: DEBUG
      PORT: '8080'
    ports:
      - "8080:8080"
    networks:
      - main
  db:
    image: "postgres:16"
    restart: unless-stopped
    environment:
      POSTGRES_DB: rust-todo
      POSTGRES_PASSWORD: assowrd
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - main
