# fly.toml app configuration file generated for rust-todo on 2023-10-05T14:20:35+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rust-todo"
primary_region = "cdg"

[build]

[[http_service.checks]]
grace_period = "5s"
interval = "60s"
method = "GET"
timeout = "5s"
path = "/ping"

[env]
RUST_LOG = "DEBUG,ht-rs-api,utils,migration,entity,views,hyper_util=info,rustls=info"

[deploy]
strategy = "canary"

[http_service]
internal_port = 8889
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
