HOST_NAME = "http://localhost:8080"
DATABASE_URL = "postgres://postgres:assowrd@localhost/rust-todo"
oauth_autodiscover_url = "http://localhost:8888/realms/master"
OAUTH_CLIENT_ID = "hyper-tarot"
OAUTH_CLIENT_SECRET = "pTcLmIRucCYWHV1MFw7Nu88xRLNozeHY"
WWW_STATIC_FILES = "./views/www"
COOKIE_SECRET = "mDMEZkjeHBYJKwYBBAHaRw8BAQdAHvl2ZWlyYSBkYSBTaWx2YSA8c2Ftb3NhYXJhQGdtYWls"
# JWKS_URL = "http://localhost:8888/realms/master/protocol/openid-connect/certs"
RUST_LOG = "DEBUG"
