[package]
name = "views"
publish = false
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
name = "views"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }

maud = { version = "0.26", features = ["axum"] }
axum = { workspace = true }
axum-macros = { workspace = true }

[lints]
workspace = true
