[package]
name = "utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }

axum = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
log = { workspace = true }

axum-extra = { version = "0.9", features = ["cookie"] }
serde_json = "1"
reqwest = { version = "0.12", features = [
    "json",
    "rustls-tls",
], default-features = false }

[lints]
workspace = true
