[package]
name = "utils"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false

[lib]
name = "utils"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }

axum = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
openidconnect = { workspace = true }
reqwest = { workspace = true }

axum-extra = { workspace = true }
serde_json = "1"

[lints]
workspace = true
