[package]
name = "rust_todo_api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
entity = { path = "../entity" }
migration = { path = "../migration" } # depends on your needs
views = { path = "../views" }

axum = "^0.7.0"
axum-macros = "^0.4.0"
futures = "0.3.30"
log = "0.4.20"
jsonwebtoken = { version = "9", default-features = false }
reqwest = { version = "0.11", features = [
    "json",
    "rustls-tls",
], default-features = false }
sea-orm = { version = "^0.12.0", features = [
    "sqlx-postgres",
    "runtime-tokio-rustls",
    "macros",
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.7", features = ["runtime-tokio", "tls-rustls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
tower-http = { version = "0.5", features = ["trace", "fs", "set-header"] }
tower-service = "0.3"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[lints]
workspace = true
