name: Deploy on Fly.app
# run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - push

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: registry.fly.io
      #     username: x
      #     password: ${{ secrets.FLY_API_TOKEN }}
      # - name: Build and push
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     push: true
      #     tags: user/app:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
