name: Deploy to Fly
# run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - push

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    name: "Build and deploy"
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - run: |
          cargo clippy
          cargo fmt --check
          cargo build --release --locked
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: rust-todo:${{github.sha}}
          cache-from: type=gha
          cache-to: type=gha,mode=min
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy -i $IMAGE_NAME
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          IMAGE_NAME: rust-todo:${{github.sha}}
