name: Deploy to Fly
# run-name: ${{ github.actor }} is learning GitHub Actions
on:
  - push

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    name: "Checks with clippy and rustfmt"
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: Lint & Build
        run: |
          cargo fmt -q --check && echo Rust-fmt successful
          cargo clippy --locked -- -D warnings && echo Clippy successful
